name: ci

on: push

jobs:

  ci:
  
    env:
      PORT: 3009
      SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PLATFORM_URI: 'http://localhost:3002'
      SERVER_URI: 'http://localhost:3000'
      SERVER_EMAIL: 'karanikio@auth.gr'
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      AUTHTOKEN1: ${{ secrets.AUTH_TOKEN1 }}
      AUTHTOKEN2: ${{ secrets.AUTH_TOKEN2 }}
      DUMMYPASS2: ${{ secrets.DUMMYPASS2 }}
      
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run test1
        run: npm test1
      - name: Run test2
        run: npm test2

  cd:

    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ./se2/9/se2-backend
            git reset --hard origin/main
            git pull https://${{ secrets.CLONE_TOKEN }}@github.com/SoftwareEngineering2-Assignment/se2-backend-group-9 main
            bash -ci 'npm install'
            bash -ci 'pm2 restart se2-backend-9'
