name: ci

on: push

jobs:

  ci:
  
    env:
      PORT: 3009
      SERVER_SECRET: ${{ secrets.SERVER_SECRET }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PLATFORM_URI: 'http://localhost:3002'
      SERVER_URI: 'http://localhost:3000'
      SERVER_EMAIL: 'karanikio@auth.gr'
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      AUTHTOKEN1: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1bW15IiwiaWQiOiI2MzhlNDA5MTMxMmRiMTRjNmVjMzBlNmYiLCJlbWFpbCI6ImR1bW15QGdtYWlsLmNvbSIsImlhdCI6MTY3MDQxNjE5M30.g4hEfpH6EoN5JaBUU-O67uv4v9nUIiWtpHCLA3_cSSg'
      AUTHTOKEN2: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImR1bW15MiIsImlkIjoiNjM4ZTRiM2QwNjE4ZTIyMTZjMGFjODMzIiwiZW1haWwiOiJkdW1teTJAZ21haWwuY29tIiwiaWF0IjoxNjcwODU1MTc5fQ.yHEuC1ssqKy0YUumB4G_krPZHwSFCviSE55MaJweWeA'

      DASHBOARD0ID: '63973c77b28f93494ec19fa3'
      WRONGDASHID: '6390be757de6d2fa567a3e34'
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test

  cd:

    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ./se2/9/se2-backend
            git reset --hard origin/main
            git pull https://${{ secrets.CLONE_TOKEN }}@github.com/SoftwareEngineering2-Assignment/se2-backend-group-9 main
            bash -ci 'npm install'
            bash -ci 'pm2 restart se2-backend-9'
